### ISSUE TITLE
Destructuring assignment in regl-line2d breaks usage in IE11

### ISSUE THREAD

**Issue by bkomboz** [a-vis/regl-line2d#32]
I am a user of `plotly.js` (version `1.37.1`) which depends on `regl-line2d` (version `^3.0.9`). The destructuring assignment used in file `index.js` in `regl-line2d` is not compatibly with any version of Internet Explorer (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment ) and therefore breaks my app. I get an error `script 1010 expected identifier`.

**Comment by dy** [comment]
That will be fixed soon, for now please use babelify global transform or dist/plotly.js entry.

**Comment by bkomboz** [comment]
Ok, thanks for the immediate feedback.

**Comment by dy** [comment]
This should be fixed now.
